# Status Constants
STATUS_STARTING = 'STARTING'
STATUS_RUNNING = 'RUNNING'
STATUS_STOPPED = 'STOPPED'

# Event Type Constants
EVENT_APP_STARTED = 'APPLICATION_STARTED'
EVENT_TIMER_TICK_SEC = 'TIMER_TICK_SEC'
EVENT_TIMER_TICK_MIN = 'TIMER_TICK_MIN'
EVENT_PROGRAM_STARTED = 'PROGRAM_STARTED'
EVENT_PROGRAM_COMPLETED = 'PROGRAM_COMPLETED'


