# Status Constants
STATUS_STARTING = "STARTING"
STATUS_RUNNING = "RUNNING"
STATUS_STOPPED = "STOPPED"

# Event Type Constants
# App
EVENT_APP_STARTED = "APPLICATION_STARTED"
# Timer
EVENT_TIMER_TICK_MIN = "TIMER_TICK_MIN"
EVENT_TIMER_TICK_SEC = "TIMER_TICK_SEC"
# Program
EVENT_PROGRAM_COMPLETED = "PROGRAM_COMPLETED"
EVENT_PROGRAM_STARTED = "PROGRAM_STARTED"
EVENT_PROGRAM_UPDATED = "PROGRAM_UPDATED"
# Zone
EVENT_ZONE_CHANGED = "ZONE_CHANGED"
EVENT_ZONE_ADDED = "ZONE_ADDED"
EVENT_ZONE_DELETED = "ZONE_DELETED"
EVENT_ZONE_UPDATED = "ZONE_UPDATED"
EVENT_ZONES_UPDATED = "ZONES_UPDATED"
