# Status Constants
STATUS_STARTING = "STARTING"
STATUS_RUNNING = "RUNNING"
STATUS_STOPPED = "STOPPED"

# Event Type Constants
# App
EVENT_APP_STARTED = "APPLICATION_STARTED"
# Timer
EVENT_TIMER_TICK_MIN = "TIMER_TICK_MIN"
EVENT_TIMER_TICK_SEC = "TIMER_TICK_SEC"
# Program
EVENT_PROGRAM_STATE = "PROGRAM_STATE"
EVENT_PROGRAM_COMPLETED = "PROGRAM_COMPLETED"
# Zone
EVENT_ZONE_STATE = "ZONE_STATE"
# Plugins
EVENT_PLUGIN_LOADED = "PLUGIN_LOADED"
EVENT_PLUGINS_COMPLETE = "PLUGINS_COMPLETE"
