"""'add_schedule_type'

Revision ID: 13c7d8cbca17
Revises: 3a9ce24f77e3
Create Date: 2020-06-14 20:38:32.013077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13c7d8cbca17"
down_revision = "3a9ce24f77e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule",
        sa.Column(
            "schedule_type", sa.String(length=15), nullable=True, default="Weekly"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "schedule_type")
    # ### end Alembic commands ###
